spring:
  application:
    name: techinsights-article
  cloud:
    nacos:
      config:
        username: nacos
        password: SSSddd111222333
        namespace: techinsights
        server-addr: 117.68.98.61:8848
        group: DEFAULT_GROUP
      discovery:
        username: nacos
        password: SSSddd111222333
        namespace: techinsights
        server-addr: 117.68.98.61:8848
  config:
    import:
      - optional:nacos:techinsights-database.properties?group=DEFAULT_GROUP?refresh=true
      - optional:nacos:techinsights-article.properties?group=DEFAULT_GROUP?refresh=true